### ISSUE TITLE
I have a problem using your configuration.

### ISSUE THREAD

**Issue by UZIhuhuhu** [dceddia/create-react-app-customized#4]
### ERROR
```
$ node scripts/customized-config start
undefined:1
config
^

ReferenceError: config is not defined
    at eval (eval at __get__ (/Users/huangxingyuan/Green-Pomelo/project-code/qy-graph-bed/node_modules/react-scripts/scripts/start.js:140:16), <anonymous>:1:1)
    at Object.__get__ (/Users/huangxingyuan/Green-Pomelo/project-code/qy-graph-bed/node_modules/react-scripts/scripts/start.js:140:16)
    at rewireModule (/Users/huangxingyuan/Green-Pomelo/project-code/qy-graph-bed/scripts/customized-config.js:77:27)
    at Object.<anonymous> (/Users/huangxingyuan/Green-Pomelo/project-code/qy-graph-bed/scripts/customized-config.js:18:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**How can I resolve it?**

**Comment by UZIhuhuhu** [comment]
I use the dependency `react-app-rewired` to solve the problem :)

**Comment by themrxcm** [comment]
> I use the dependency `react-app-rewired` to solve the problem :)

Hi! Why didn't you share an example solution?
